### ISSUE TITLE
Should new handbook have an "Assessment" section? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#101]
This is the assessment section in the current handbook: https://docs.carpentries.org/topic_folders/assessment/index.html

My feeling is that all this content is best suited for the main website.

**Comment by klbarnes20** [comment]
I think I agree with you @maneesha. All of that info can go on the website. All of the rest of our assessment materials are internal facing right now. That being say, as you improve feeds.carpentries.org, we may come across information we want to share with the community about how to use the feeds. But I don't think we need that right now.

**Comment by maneesha** [comment]
Thanks @klbarnes20 I'm closing this for now and we can come back to it later if needed.
