### ISSUE TITLE
Consider using MyST instead of reST file format

### ISSUE THREAD

**Issue by dpshelio** [carpentries/handbook-beta#105]
Years ago I suggested migrating to reST (https://github.com/carpentries/docs.carpentries.org/issues/506), and now that we are doing it... I'm proposing to consider using [MyST](https://myst-parser.readthedocs.io/en/latest/intro.html) instead, as @astrojuanlu [recommended in that original issue](https://github.com/carpentries/docs.carpentries.org/issues/506#issuecomment-1513698887).

For the little bit I've seen MyST, it seems great, it will work with sphinx seamlessly and the format is very similar to the one for the lessons used with sandpaper. Also, if everything is using the same format, the translations could also happen at that level. (I haven't explored yet the internasiolasation integration, but if all the files are using the same format I believe the process will be easier than how it was in the previous handbook).

As @juanlu also pointed out in the previous issue, there are tools to convert [rst-to-myst](https://github.com/executablebooks/rst-to-myst) that could convert the whole thing at once.

**Comment by maneesha** [comment]
Closing this as we are migrating docs to myst.
