### ISSUE TITLE
Community session Host (Slack quick start guide)

### ISSUE THREAD

**Issue by elletjies** [carpentries/handbook-beta#112]
## Community Sessions

The Carpentries Community Engagement Team manages Community Sessions which are led by Community Session Hosts. This section of the handbook describes how community sessions are organised and conducted.    

The Carpentries Community Sessions are designed for everyone in The Carpentries community interested in learning, educating, and advocating for teaching foundational coding and data science skills globally. Session topics range anywhere from teaching workshops and developing curricula to building local communities and assessing the impact of our workshops. There are three types of Community Sessions:

1. __Community Discussion Session__ structured (e.g., panel discussion with Q&A) or flexibly structured session (e.g., networking session) on any topic relevant to the community that can be in any format of the host’s choosing

2. __Skill-up Session__ session offering a professional development opportunity for the community where hosts teach relevant skills

3. __Collaboration Session__ session providing dedicated time and space to co-develop a community resource or to co-work on any community activity

### Who Can Host?

Hosting community sessions is a great way to meet more people in The Carpentries community, get to know the organisation better, learn from the experiences of others, and share your knowledge and experience with an even greater number of people.

Any member of The Carpentries community is welcome to host a community session. Sessions are coordinated by The Carpentries Community Engagement Team. To receive messages relating to sessions and hosting, make sure that you are subscribed to the [session hosts mailing list](https://carpentries.topicbox.com/groups/discussion-hosts) or follow the #discussion-hosts channel on the Slack workspace.

A great way to get into hosting these sessions is to first attend as an observer or co-host. An experienced host will be happy to talk you through it and may return the favor when you host for the first time.

#### Session Host Onboarding

If you are interested in becoming a Community Session Host it will take ~45 minutes of your time to get onboarded. Instructions are provided below.

1. **Watch the onboarding video.** [The video can be found on our YouTube channel](https://youtu.be/gM-XXV07OtQ) and you can also view the accompanying [slides](https://docs.google.com/presentation/d/1HzvrQrUljqZRdyw85KviCg3txtMJb4V235wWGRhZrUU/edit?usp=sharing). Once you have watched the video or gone through the presentation, please [send an email](mailto:community@carpentries.org) with the subject "Community Session Host Onboarding" so we can record that you have been onboarded to the role.

### Scheduling Community Sessions

Except for some sessions led by our subcommunities, community sessions are scheduled quarterly [as described here](../communications/guides/community_events.md). This allows The Carpentries Community Engagement Team to support your recruitment initiatives and help publicise your event. In the rare instance that you need to schedule such sessions outside of the quarter scheduling period, please [contact us](mailto:community@carpentries.org). Your session is not confirmed until you hear from a member of The Carpentries Community Engagement Team.

### Community Session Host Checklist

Community sessions are organised and conducted through the community session Etherpad, which is updated each year (https://pad.carpentries.org/community-sessions-YYYY). Many regional subcommunities use their notetaking platform. Links to these can be found at the top of the community session Etherpad and are available in the relevant event on our [Community Calendar](https://carpentries.org/community/#community-events).

#### Before the Discussion Session 

- Be sure to sign on at least five minutes before the call so you can welcome community members as they sign on. Introduce yourself as the host and add a link to where the notes will be captured in the Zoom chat.  
- Add the agenda for your session to the notes. If you use the Community Sessions Etherpad for notetaking, copy and paste your agenda under the space where participants sign up to attend.
- Assign a notetaker if needed.
- Claim host by following the instructions shared with you in your session confirmation email. If you did not receive a confirmation email, [contact the Community Development Team](mailto:community@carpentries.org).  

#### During the Discussion Session 

- Welcome, introductions, and reminder of Code of Conduct  
  - [Code of Conduct Link](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
- Provide multiple options for participation (e.g. raise hand feature in Zoom, type question into chat)
- Don’t feel like you have to answer all the questions as the host. Draw on other participants to answer questions.
- Try to leave enough time at the end (~5 minutes) for final reflections.
- Thank attendees for participating

#### After the Discussion Session

- Archive the Etherpad by clicking "Save Revision" which displays as star in the features panel.  
- Fill out the [host questionnaire](https://forms.gle/N74pFuGkRLawpCHh7)
    - Note: Please copy the list of attendees (including all attendees but removing no-shows) and paste it into the questionnaire.
    - This questionnaire will automatically send an email to the Instructor Development Committee Co-Chairs and to instructor.training@carpentries.org.
- If you used the Community Sessions Etherpad for notetaking and would like to save your notes, be sure to export the Etherpad by clicking "Export/Import" which displays as two arrows in the features panel. Remind attendees to do the same.
- Clear the information from your session (date/time, attendees, notes) from the Etherpad.
- (Optional) Write a [blog post](https://docs.carpentries.org/topic_folders/communications/submit_blog_post.html#how-to-contribute-a-blog-post-to-the-carpentries-blog) about your session.

### Discussion Session FAQ

A portion of the content below comes from [this blog post](https://carpentries.org/blog/2019/05/community-discussions-primer/).

##### What if I do not know the answer to someone's questions and no one in the room does either?

It is totally fine if you do not know all the answers. In such a situation you are welcome to refer the question to someone within The Carpentries community that will have the answer. If not, you could always send your question to [community@carpentries.org](mailto:community@carpentries.org).

##### What if the host/co-host has a poor internet connection and is unable to communicate? What if Zoom fails to work (e.g. your internet connection fails?)

It is very important to test your internet connection beforehand and to make sure that you as a host can communicate. The host is the session leader and should have a stable connection. If, however, when you test your connection you find that you do not have a good connection, reach out to the community to see if someone could take over as host for that session. Do this by sending a message to the discussion-hosts channel on Slack or [discussion-hosts on TopicBox](https://carpentries.topicbox.com/groups/discussion-hosts).

##### What if a group from a single site has connectivity issues?

You could ask them to try and reconnect. However, if they continue to have issues and cannot participate in the session, please ask them to reschedule.

##### What if no one shows up?

If no one shows up simply wait for a few minutes, send out reminder emails to the signed-up participants, and then fill in the post-discussion questionnaire and indicate that no one showed up for your session.

##### What if someone talks too much?

Limit the amount of time that you give participants to ask and answer questions. You could ask for feedback from someone who has not spoken yet as well.

##### What if there is no co-host/note taker and the session is fully booked?

As a host you are more than welcome to take a few notes, however there is no need to take down every single thing that is said. Note down important points, making sure to add links to useful information. Also, encourage the participants to contribute to the notes on the Community Discussions Etherpad(https://pad.carpentries.org/community-sessions-YYYY).

##### What if someone joins in late?

Depending on how late the person joins, you could simply welcome them and ask them to introduce themselves to the rest of the participants. If you have time, you can ask the individual to stay on the call for a few minutes after it is finished to summarise what they missed and answer any questions they may have.

##### What if someone does not have a headset and can’t control their background noise?

As a host, you will have the privilege to mute other participants, or you could simply ask the person directly to mute their microphone.  Read more about how to use [host features in Zoom](https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html#information-for-event-hosts).

##### What if I forget to complete the host questionnaire?

The participants will not have updated profiles for the checkout sessions and it will take a lot of administration to solve this challenge. Please remember to fill in the form directly after hosting your session.

##### What if someone breaks the Code of Conduct? What if someone had a report of misconduct?

In the case that this happens The Carpentries has a set of [guidelines](https://docs.carpentries.org/topic_folders/policies/incident-response.html) that can be followed.

##### What if someone asks me to join the session and it is already full?

Participants can email the host directly and ask if it would be ok with them if they joined the session although it is already fully booked.

##### What if someone talks down to other people?

It is very important to remind everyone of the [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/index_coc.html) as The Carpentries observes it in every community event. This will be a clear violation of this and you could ask the person to leave.

##### What if I am having trouble understanding one of the attendees?

You could ask the participant to type their questions in the Community Sessions Etherpad for you to read and respond to them, which will also make note-taking much easier. Consider asking them to speak louder if the microphone is too soft.

**Comment by maneesha** [comment]
@elletjies it looks like you have copied over content from the current handbook.  
We also have content in the new handbook (https://carpentries-beta-handbook-preview.netlify.app/community/community_session_host).  Our goal is to make each community role's handbook follow the same format, so that a user coming to each of them will have the same experience.  Can we consolidate this so it follows this format: 

- Description of Role	
- Roles and responsibilities
- Communication and Collaboration Spaces
- Step-by-Step Guide
- Meeting Checklists
- Resources
- FAQ
-

**Comment by elletjies** [comment]
@maneesha thanks - I will need to work more on this during the next round. Is this ok?

**Comment by maneesha** [comment]
Yes - please do!

**Comment by elletjies** [comment]
@maneesha will it be possible to only have the content in the handbook and then link it back from the Carpentries website?

**Comment by maneesha** [comment]
@elletjies Yes, that is the plan.  The content will be in the handbook and linked to on The Carpentries website (and where ever else you want to link to it)

**Comment by elletjies** [comment]
@maneesha can we change the schedule https://carpentries-beta-handbook-preview.netlify.app/community/community_session_host#id1 to have the grey scale like here https://carp-new-website.netlify.app/support/sponsorship/. It might make it easier to read

**Comment by elletjies** [comment]
I am working on this PR - https://github.com/carpentries/handbook-beta/issues/112

**Comment by maneesha** [comment]
@elletjies some of your changes to this section came in before it was actually ready for review, so it would be good to have you look over this again to be sure all your suggestions were incorporated.

See here:  https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host

**Comment by elletjies** [comment]
@maneesha some notes: 

- the community discussion Etherpad link is - https://pad.carpentries.org/community-sessions-2024
- Slack Quick Start Guide - @OscarSiba have you completed this? It is currently linking to the old handbook page
- I have made changes here: https://github.com/carpentries/handbook-beta/pull/159

**Comment by maneesha** [comment]
@elletjies I have fixed the Etherpad link and merged your PR #159.

Leaving this open to check in about the Slack Quick Start Guide.

**Comment by maneesha** [comment]
I discussed with @OscarSiba today.  We will keep the Slack guide as a google doc and link to it from the Handbook.  The Handbook will not contain any content about the Slack guide.

**Comment by elletjies** [comment]
@OscarSiba can we then do the same for the TopicBox guide (and any other guides we have developed)

**Comment by maneesha** [comment]
Closing this issue.  We are linking to guides on Google Docs.
