### ISSUE TITLE
Investigate encoding/decoding of email addresses

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#123]
Email addresses are sometimes rendered with `%40` instead of `@`

**Comment by maneesha** [comment]
@froggleston  If you have some time to help me figure this out, that would be great.

**Comment by maneesha** [comment]
I thought it was just sometimes, but this does seem to happen pretty consistently.  Just a couple of examples: 

* [...you can email the Community Development Team to inform them...](https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host#onboarding) ([source](https://github.com/carpentries/handbook-beta/blob/main/source/handbooks/community_session_host.md?plain=1#L69))
* [...please email the Curriculum Team...](https://carpentries-beta-handbook-preview.netlify.app/handbooks/curriculum_advisors#about-this-handbook) ([source](https://github.com/carpentries/handbook-beta/blob/main/source/handbooks/curriculum_advisors.md?plain=1#L506))

**Comment by froggleston** [comment]
From reading around, this seems to be commonplace to avoid spamming of mailto links hoovered up by web scrapers/crawlers. When clicking the link, it opens the typical mailto prompt to choose a mail client, so the normal functionality isn't affected.

**Comment by maneesha** [comment]
Thanks @froggleston 
In that case can we close this issue?

**Comment by froggleston** [comment]
I think so!
