### ISSUE TITLE
Deprecate newsletter section of handbook

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#128]
I am recommending deprecating the [newsletter section of the handbook](https://docs.carpentries.org/topic_folders/communications/tools/newsletter.html#) because it applies only to internal Core Team workflows.  @OscarSiba please let me know what you think.

**Comment by OscarSiba** [comment]
Yes, please deprecate this section.

**Comment by maneesha** [comment]
We will not move the newsletter section to the new handbook.
