### ISSUE TITLE
Review Lesson Developers Handbook

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#135]
See https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_developers

Please consider the following when you review:

- [ ] Is all the content accurate?
- [ ] Do the links all work?
- [ ] Have you noticed any content duplicated in other places? 
- [ ] Any other feedback or suggestions

**Comment by tobyhodges** [comment]
[My questions on #155](https://github.com/carpentries/handbook-beta/issues/155#issuecomment-2429149927) are relevant to this issue.

**Comment by maneesha** [comment]
Closing this to address in the Curriculum Resources issue.
