### ISSUE TITLE
Review Maintainers Handbook

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#136]
See https://carpentries-beta-handbook-preview.netlify.app/handbooks/maintainers

Please consider the following when you review:

- [ ] Is all the content accurate?
- [ ] Do the links all work?
- [ ] Have you noticed any content duplicated in other places? 
- [ ] Any other feedback or suggestions

**Comment by tobyhodges** [comment]
Notes from initial review on 2024-10-22:

- Please remove the _Curriculum Development Handbook_ section.
- In https://carpentries-beta-handbook-preview.netlify.app/handbooks/maintainers#adding-topic-tags-to-a-lesson-repository, the table is not appearing correctly.
- The whole subsection of https://carpentries-beta-handbook-preview.netlify.app/handbooks/maintainers#adding-topic-tags-to-a-lesson-repository should be moved to the equivalent part of the _Lesson Developer Handbook_.
- The link to the Collaborative Lesson Development Training curriculum, which appears after the section about the CDH, can be removed.
- Please remove the FAQ section for now.

@ErinBecker, @froggleston and I are working on some more new content to help Maintainers handle the automated infrastructure updates that  come into their repositories. I will post back here with more on that ASAP.

**Comment by maneesha** [comment]
Draft PR is up; awaiting response to question above.

**Comment by tobyhodges** [comment]
> @tobyhodges to be clear, you want to to have the topic tags section moved to the Lesson Developer Handbook (and not appear in the Maintainer Handbook)?

Yes, that's right. I do not think this information is relevant to Maintainers.

**Comment by maneesha** [comment]
This is addressed with #205
