### ISSUE TITLE
Review Instructor Trainers Handbook

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#137]
See https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructor_trainers

Please consider the following when you review:

- [ ] Is all the content accurate?
- [ ] Do the links all work?
- [ ] Have you noticed any content duplicated in other places? 
- [ ] Any other feedback or suggestions

**Comment by sheraaronhurt** [comment]
- **Attendance Policy** should go under the [Instructors Onboarding](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#onboarding) under the first bullet regarding attend an Instructor Training
- **Checkout Extension** should go under [Instructors Onboarding](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#onboarding) under the second bullet regarding checkout
- **Scheduling Training Events** should go under [Roles & Responsibilities](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructor_trainers#roles-and-responsibilities) at the end of the section
- **Email Templates** can be removed as those are internal emails that we already have stored in Helpscout

**Comment by sheraaronhurt** [comment]
I have made all of the edits in [this document](https://docs.google.com/document/d/1OyUtzwoGNJl2_JAFssEBADXwwf4YfkNu6RORmh43Mgo/edit?tab=t.0). Please copy and paste everything from the document to the Handbook. There are a few questions that I have asked from a few Core Team Members that I will have to adjust during the next iteration.

**Comment by maneesha** [comment]
Addressed with #186
