### ISSUE TITLE
Review Communications Resources page (and all the pages linked from there)

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#140]
See https://carpentries-beta-handbook-preview.netlify.app/resources/communications/

This combines what is currently in the various communications menus on to one landing page.  Content for each page has been taken directly from the existing pages.

- [ ] Communications tools landing page
- [ ] Collaborative Documents (Etherpads, Codimd)
- [ ] Styles, Branding, and Logos
- [ ] Communication spaces (Slack, Topicbox, Zoom)
- [ ] Carpentries Commons
- [ ] Presentations

**Comment by OscarSiba** [comment]
This is great Maneesha, but please modify order as follows:

- [ ] Collaborative Documents (Etherpads, Codimd)
- [ ]  Communication spaces (Slack, Topicbox, Zoom)
- [ ]  Styles, Branding, and Logos
- [ ]  Presentations
- [ ]  Carpentries Commons and Zenodo (and then add a link to our Zenodo account: https://zenodo.org/communities/carpentries/records?q=&l=list&p=1&s=10&sort=newest
