### ISSUE TITLE
Where should Committee Guidelines go? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#144]
This is what we currently have:  https://docs.carpentries.org/topic_folders/governance/committee-guidelines.html

Where in our new handbook should this go?

**Comment by kariljordan** [comment]
Related: https://github.com/carpentries/handbook-beta/issues/147, https://github.com/carpentries/handbook-beta/issues/146, https://github.com/carpentries/handbook-beta/issues/145

The current version of our handbook has a section called [Policies](https://docs.carpentries.org/topic_folders/policies/index.html). We also have a section for Policies in the new handbook. Can all of the policies and guidelines go there, and we rename it **Policies and Guidelines**?

Or, if we want to separate legal/business operational policies (e.g., privacy policy) from policies that are more community management (e.g., instructor no-show policy), we can do that.

**Comment by maneesha** [comment]
We currently have resources including Communications Resources, Curriculum Resources,
Workshops Resources. 
I discussed with @OscarSiba.  We will include another section called "General Resources" and include Task Force and Committee Guidelines there (and any other such guidelines as they come up).  This will include programmatic policies and guidelines, as distinct from business or legal policies.

**Comment by maneesha** [comment]
Addressed with #191
