### ISSUE TITLE
Where should Lesson Program policy go?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#146]
We have this in our current handbook: https://docs.carpentries.org/topic_folders/governance/lesson-program-policy.html

Where should this go in our new handbook?  If it is a "policy" in the same sense as all the others, we can add it to the policy section.

**Comment by tobyhodges** [comment]
- [Lesson Program Governance Policy](https://docs.carpentries.org/topic_folders/governance/lesson-program-policy.html#lesson-program-governance-policy) should go into the _Policy_ section. Link the first instance of "Lesson Program" to the section on Lesson Programs undr _Curriculum Resources_
- All other content on this page should be used to create a new section, titled _Lesson Programs_ linked from _Curriculum Resources_. I may need to add a bit more content to guide people to relevant information on existing LPs i.e. the _About_ and _Governance_ pages of the LP websites

**Comment by maneesha** [comment]
I discussed with @OscarSiba 
This is not a "policy" in the same sense as Privacy Policy, Cookie Policy, etc. It applies more to our internal operations.  We recommend including it in the [Curriculum Resources page](https://carpentries-beta-handbook-preview.netlify.app/resources/curriculum/), and linking to it wherever needed.

**Comment by maneesha** [comment]
Addressed with #206
