### ISSUE TITLE
Where should IT Admin  policies and procedures go?  

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#147]
This is what is in our current handbook:
https://docs.carpentries.org/topic_folders/instructor_training/index.html#administrative-policies-and-procedures

Where should this go in our current handbook?

**Comment by sheraaronhurt** [comment]
- **Attendance Policy** should go under the [Instructors Onboarding](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#onboarding) under the first bullet regarding attend an Instructor Training
- **Checkout Extension** should go under [Instructors Onboarding](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#onboarding) under the second bullet regarding checkout
- **Scheduling Training Events** should go under [Roles & Responsibilities](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructor_trainers#roles-and-responsibilities) at the end of the section
- **Email Templates** can be removed as those are internal emails that we already have stored in Helpscout
