### ISSUE TITLE
Where should lesson development materials go? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#148]
This is what is in our current handbook: https://docs.carpentries.org/topic_folders/lesson_development/index.html

Where should this go in our new handbook?

**Comment by tobyhodges** [comment]
* CAC content is reproduced in the _Curriculum Advisor Handbook_
* Curriculum Onboarding Materials section can be moved to its own page and linked from the _Resources_ section of
    * the _Curriculum Advisor Handbook_
    * the _Lesson Developer Handbook_
    * the _Curriculum Resources_ page
* Lesson Infrastructure Subcommittee content can be removed in the transition
* Lesson Sprint Recommendations will be moved from the _Curriculum Development Handbook_ into a new page of this site (PR incoming!), and should then be linked from the _Resources_ section of 
    * the _Lesson Developer Handbook_
    * the _Maintainer Handbook_
    * the _Curriculum Resources_ page
* Lesson Pilot Workshops info should be moved to its own page, and linked from
    * the _Resources_ section of the _Lesson Developer Handbook_
    * the _Curriculum Resources_ page
* Lesson release process and schedule page, including release checklist, will be updated and moved to its own page (I will open a PR), then linked from
    * the _Lesson Developer Handbook_
    * the _Maintainer Handbook_
    * the _Curriculum Resources_ page
* Incubator lesson spotlight info should be added to the _Step by Step Guides_ section of the _Lesson Developer Handbook_

**Comment by maneesha** [comment]
@tobyhodges can you review and let me know if the changes made cover everything here?

**Comment by tobyhodges** [comment]
@maneesha Thanks for your help. I have converted the points in the list above into checkboxes, to indicate which items have been addressed. Please let me know if there are any tasks you would like the Curriculum Team to take on.

**Comment by tobyhodges** [comment]
The Curriculum Onboarding Materials page is here: https://docs.carpentries.org/topic_folders/lesson_development/curriculum_onboarding.html

The Lesson Release page can be linked from the Resources section of the handbooks.

**Comment by maneesha** [comment]
The additional links are now included in PR #183
