### ISSUE TITLE
Are we still doing Carpentries Champions and Meetups?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#149]
See what is in our current handbook here: 
https://docs.carpentries.org/topic_folders/for_instructors/current_instructors.html#carpentries-champions

Are we still doing this? If so, where should this information be?

**Comment by maneesha** [comment]
I **think** @elletjies  is the right person to ask this of, but please let me know if it should be someone else.

**Comment by elletjies** [comment]
@maneesha no we are not doing anything Championship-related. We can remove this information.
