### ISSUE TITLE
Do we want to include how to submit a blog post?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#150]
This is what is in our current handbook: https://docs.carpentries.org/topic_folders/communications/guides/submit_blog_post.html  and https://docs.carpentries.org/topic_folders/communications/guides/select-blog-tags.html

Do we want to include this in the new handbook? Where would it go?

**Comment by maneesha** [comment]
I think I remember @elletjies saying she wanted to take this section out, but I want to make sure.

**Comment by elletjies** [comment]
@maneesha I think we should leave it in - it could live under resources (create another section, other resources)

**Comment by OscarSiba** [comment]
Please move this to the newly created Communications Resources page, thanks Maneesha.

**Comment by maneesha** [comment]
@elletjies @OscarSiba Note a [previous (old) plan](https://github.com/carpentries/handbook-beta/issues/103#issuecomment-1513726760) for the website recommended removing this information.

**Comment by elletjies** [comment]
@maneesha I like this! Thank you for linking it.

**Comment by OscarSiba** [comment]
Ok, not a problem. You can remove this section and close this issue @maneesha.
