### ISSUE TITLE
Include section on submitting announcements/job postings? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#151]
This is what we have in our current handbook:  
https://docs.carpentries.org/topic_folders/communications/guides/submit-news-item.html
and
https://docs.carpentries.org/topic_folders/communications/guides/share-opportunities.html

Do we want to include this in our new handbook? Where would it go?

**Comment by OscarSiba** [comment]
- [ ] Please delete the section on Sharing Relevant Announcements: https://docs.carpentries.org/topic_folders/communications/guides/submit-news-item.html.

- [ ] Then please modify the section on "Sharing Postings on Carpentries Clippings" in this link https://docs.carpentries.org/topic_folders/communications/guides/share-opportunities.html to read as follows: 

_Carpentries Clippings_ is a monthly newsletter to members of our community featuring community news, program updates of note, and opportunities relevant to the wider Carpentries community.

If you would like to share a job posting that we will feature in Carpentries Clippings, please email [community@carpentries.org](mailto:community@carpentries.org) with _For Newsletter_ as the subject line.

**Comment by maneesha** [comment]
Closing this issue.  Will reconsider with #187
