### ISSUE TITLE
What should go on Tip Sheet page? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#153]
Review Tip Sheet page.  See https://carpentries-beta-handbook-preview.netlify.app/resources/tip-sheets

What general information should be on this page?  What tip sheets should be listed on this page? 

@elletjies  Please don't try to edit the page itself as I need to set up some custom link formatting.  You can share whatever should be on that page here in this issue.

**Comment by elletjies** [comment]
We currently have 2 tipsheets (but other resources too). I will add the tip sheet links here:

- Welcome Tip Sheet: https://zenodo.org/records/10785524
- Instructor Onboarding: https://zenodo.org/doi/10.5281/zenodo.8125137

**Comment by maneesha** [comment]
Addressed with #178
