### ISSUE TITLE
What should be in Workshops resources page? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#154]
We have a page for [workshops resources](https://carpentries-beta-handbook-preview.netlify.app/resources/workshops).  What should go on this page?

Consider things like online workshop recommendations - [see this GH issue](https://github.com/carpentries/new-website/issues/209).

**Comment by sheraaronhurt** [comment]
@maneesha I am reassigning to @danielle06 . We discussed removing Instructor Resources and placing all of their resources into the Workshop Resources.

**Comment by danielle06** [comment]
Thank you @maneesha and @sheraaronhurt - I have put in a pull request to add the workshop checklists, email templates, creating a workshop website demo video, online workshop resources, and also directed them to the tip sheet for additional

**Comment by maneesha** [comment]
Thanks both.  Closing this as I have merged the PR @danielle06 put in.
