### ISSUE TITLE
What links go in front page resources/quick links? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#156]
See the front page: https://carpentries-beta-handbook-preview.netlify.app/

There is a section for "Resources" and a section for "Quick links."  What resources/links should go in those two sections?

**Comment by ErinBecker** [comment]
My 🪙 🪙 

## Resources

- The Carpentries Commons hasn't been updated in a year. I recommend not including it in this link list. 
- Code of Conduct - keep
- Community Calendar - keep (but fix link, currently goes to carpentries home page)
- Community Glossary - keep
- Style Guide - keep
- Welcome Tip Sheet - keep (but fix link, currently goes to carpentries home page)

## Quick Links

- AMY database - remove
- Carpentries Incubator - remove
- Carpentries Lab - remove
- Etherpad Pad of Pads - this seems to be updated regularly, keep
- Self-Organised Workshop Notification Form - keep
- Training Website Template - keep
- Workshop Website Template - keep

**Comment by OscarSiba** [comment]
I agree with all of Erin's suggestions above, but please modify as follows:

- [ ] Move the Community Calendar out of Resources to the Quick Links section
- [ ] [A Guide for Collaborating with The Carpentries on Grants](https://docs.carpentries.org/topic_folders/fundraising/collaborating-on-grants.html) - Move this to the resources section of the handbook.
- [ ] [Donation Request Resources](https://docs.carpentries.org/topic_folders/fundraising/donation-request-resources.html) - Move this to the resources section of the handbook.
- [ ] Add a link to the [Mastodon Quick Start Guide](https://zenodo.org/records/10019853) to the Resources section.
- [ ] Add link to the [Toolkit of IDEAS](https://zenodo.org/records/10391883) to the Resources section.

**Comment by maneesha** [comment]
Addressed with #179
