### ISSUE TITLE
Hyperlink not active on Etherpad Page

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/handbook-beta#172]
The hyperlink for team@carpentries.org under [Troubleshooting](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/etherpads) is not active. however, in the edit view it shows as a hyperlink.

**Comment by froggleston** [comment]
The link is not a markdown link in the source: https://github.com/carpentries/handbook-beta/edit/main/source/resources/communications/etherpads.md so adding that would solve this issue
