### ISSUE TITLE
Re-organize lists on front page (Resources and Quick Links)

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#188]
Re-consider order of links as they appear on the front page. 
Re-consider the titles as "Resources" can be confusing since it is used elsewhere.

**Comment by maneesha** [comment]
@OscarSiba When we do this, what do you think of removing "Tip Sheets" from the left side bar and including them in "General Resources" (linked to from the sidebar) instead?

**Comment by maneesha** [comment]
@OscarSiba Let me know when you'll be working on this.  Thank you!

**Comment by OscarSiba** [comment]
Ok. 

- [ ] Please remove "Tip Sheets" as a separate resource folder, and instead it as a sub-folder under the "General Resources" folder. 
- [ ] Then under what is titled "Resources" on the main page (just above Quick Links), please rename that list to be "Popular Resources" (as a way of distinguishing it from the "Resources" heading in the side bar. 
- [ ] Then list the the resources under that heading in this order: 
- [Join The Carpentries Slack workspace](https://slack-invite.carpentries.org/)
- Welcome Tip Sheet
- Instructor Tip Sheet
- Mastodon Quick Start Guide
- A Guide for Collaborating with The Carpentries on Grants
- Donation Request Resources
- Community Glossary


- [ ] Then, under Quick Links, please list these resources in the following order:
- [Code of Conduct](https://carpentries-beta-handbook-preview.netlify.app/policies/coc)
- Community Calendar
- Etherpad Pad of Pads
- Self-Organised Workshop Notification Form
- [Toolkit of IDEAS](https://zenodo.org/records/10391883)
- Training Website Template
- Workshop Website Template
