### ISSUE TITLE
Review and explain capitalisation of instructor/Instructor in LessonDev sections

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/handbook-beta#195]
In some parts of the handbook, particularly about lesson development, we refer to instructors who have not been certified (i.e. not _Instructors_). The curriculum handbook content should be reviewed to ensure consistency, and a note should be added at the top of relevant pages to help visitors distinguish between _instructors_ and _Instructors_ within the content.

**Comment by maneesha** [comment]
@tobyhodges Let me know if you plan to get to this now. If not, please apply the "later" label.  Either way is fine; I just want to stay organized.
