### ISSUE TITLE
Updates to the donation request resources pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#208]
For this page: https://carpentries-beta-handbook-preview.netlify.app/resources/general/donation-request-resources

- [x] Please replace the Individual donation letter with [the updated text in this document](https://docs.google.com/document/d/1FRUgMTRqhGyqUuPJIMA4ok72F1aiJwBsAeIdQ5dXa7o/edit?tab=t.0). 
- [x] Please delete the Donation Request Letter - Organisation.
- [x] Under "Short Calls to Action/Mastadon Length Messages" please change the donation page URL for the third message to also read more neatly as https://give.communityin.org/TheCarpentries.
- [x]  Please delete the section on Appeal Images.

**Comment by maneesha** [comment]
Addressed with #214
