### ISSUE TITLE
Updates to Collaborating on grants page

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#209]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/general/collaborating-on-grants

- [x] Under "Request to meet one of our program leads" there is a link to the Carpentries’ [strategic priorities](https://carpentries.org/strategic-plan/), and I don't think we added this page to the new site.... 
- [x] Under "How is The Carpentries Funded?" please remove "([The Carpentries Philanthropy](https://carpentries.us14.list-manage.com/subscribe?u=46d7513c798c6bd41e5f58f4a&amp;id=33f76196ac))" in the first sentence.
- [x] Under the same heading, we again have reference to alignment with our [strategic plan](https://carpentries.org/strategic-plan/), the probably missing information on our website. 
- [x] Under "Current and Past Grants and Subawards", the URL to [Lawrence Berkeley Laboratory](https://carpentries.org/supporters/) and the [United States Department of Agriculture (USDA)](https://carpentries.org/supporters/) lead to a page we have discontinued on our old site. Please update to the following links, respectively: https://www.lbl.gov/ and https://www.usda.gov/ 
- [x] The link to [blog posts tagged grants](https://carpentries.org/posts-by-tags/#blog-tag-grants) leads to a 404 error message. On the old website, the link to the blog posts tagged grants should be: https://carpentries.org/blog/posts-by-tags/#blog-tag-grants
---

**Comment by maneesha** [comment]
@kariljordan Please see the comments from @OscarSiba about the strategic plan.  What would you like us to do here?

**Comment by maneesha** [comment]
PR #215 addresses the other points in the list above.

**Comment by kariljordan** [comment]
Please create the strategic plan page on the new website. Leave everything just as it is. I'll have updates on the next iteration of our strategic plan after the Q4 board meeting. This version of our plan goes through April 2025 (we started late because of COVID).

**Comment by maneesha** [comment]
Remaining items are addressed with #218
