### ISSUE TITLE
Updates to Curriculum resources and Workshop resources main pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#210]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/curriculum/
- [x] In keeping with the other pages, all the hyperlinked resource titles should **not** be bolded. 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/workshops/
- [x] Please spell all reference to "Helpers" with a small h. This is under the "Workshop Checklists" and "Email Templates" sentences.

---

**Comment by maneesha** [comment]
Addressed with #216 and #217
