### ISSUE TITLE
Updates to the Communications resources folder

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#211]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/
- [x] Please rename the title and/path of the page to be "Communications Resources" instead of "Communications Tools". 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/codimd
- [x] Under "Troubleshooting", please hyperlink the email. 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms
- [x] Under "General Room Usage and Links", please refer to "Instructor Trainers" and not just "Trainers" in the following sentence: "For Instructor Training events, this link will be shared with the Trainers and trainees..."
- [x] Please spell " organizer" that is at the end of that paragraph with an "s" instead of "z".
- [x] Under "Gaining Host Access" please remove the second full stop at the end of the link provided at the end of this section. 
- [x] Under "Non-verbal, real time feedback" please add a full stop at the end of the link provided at the end of this section. 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#topicbox
- [x] Please delete all the text that is currently under "TopicBox" and replace with the link to this new document instead: https://docs.google.com/document/d/1lk1KmImG-5nkYzukjFMZMTS4BEVaOkqBg5_V_aj85_U/edit?tab=t.0#heading=h.ywa9v8kainmp
- [x] Please do the same for the Slack content and replace with the link to this document instead: https://docs.google.com/document/d/1-NcL-ofnHXjJnopdWH6jLrdLHhDJeZO3/edit

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/style-guide
Not comprehensive, but some quick updates for this round of Handbook ready-ness:
- [x] Under "bullet points" under B section please refer to "Instructor Trainers" instead of just Trainers
- [x] Under same place, please replace "Mentors" with Maintainers
- [x] Then please go to the "numbered lists" under N section and apply the same two above changes. 
- [x] Under "capital letters and capitalisation" in the C section please delete reference to Supportive Instructor and Mentor roles, and also refer to "Instructor Trainer" instead of "Trainer".  
- [x] Then please go to "roles" under R section and apply the same changes there.
- [x] Under "company names" please replace reference to Twitter with Mastadon

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/brand_identity
- [x] That title "Lesson Program Colours and Shades" should be renamed "Secondary General Carpentries Colours and Shades"
- [x] And then in that section replace all reference to lesson programs with "General Carpentries". So, e.g., "Data Carpentries" and "Data Carpentries (Light)" should be "General Carpentries" and  "General Carpentries (Light)". Repeat this for SC and LC colours. 
- [x] The section title "Secondary/Supplementary Colours and Shades" should merely be "Supplementary Colours and Shades"
- [ ] Under "Carpentries Fonts", are these fonts still what we are using in the new website or do they need to be updated here? 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/logos
- [x] Under "Uses that require approval from The Carpentries", in the 5th paragraph, please change "Community Development Team" to Community Engagement Team.
- [x] The last paragraph in that section should actually be a separate section. So "License for this Policy" should be a subheading, and the rest of the text should go below it. 

On this page: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/presentations
- [x] Please replace the link to the [Carpentries Presentation Template](https://docs.google.com/presentation/d/1y0lvjLwDe34qe7gGiZiBrVLWwVuA6haw9eNDjNqxMKM/edit?usp=sharing) with this one: https://docs.google.com/presentation/d/160gj2GGepxlwJb2F0mPjUQ92aYENr8R_qulkuHXe5SU/edit#slide=id.p

---

**Comment by maneesha** [comment]
All points above are addressed with #219 except for the question about fonts.  We use [Mulish](https://fonts.google.com/specimen/Mulish) throughout our websites and handbook.  @OscarSiba Please share what you would like to say here.

**Comment by OscarSiba** [comment]
Please revise that sentence to read: "The font used in the headers and the body of the https://carpentries.org/ website and its lesson program websites is [Mulish](hhttps://fonts.google.com/specimen/Mulish)." 

Then you can close this issue, thanks.

**Comment by maneesha** [comment]
Final note about fonts is addressed in #235
