### ISSUE TITLE
Updates to the Community Session Hosts Handbook

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#212]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host
- [x] Under the Introduction, please list "Regional Community Calls" as number 2 in that list of 4 (which currently only has 3 numbered items.
- [x] Under "Mailing List", please update the The Carpentries mailing lists from [Topicbox](https://carpentries.topicbox.com/groups/latest) link with this one: https://carpentries.topicbox.com/latest 
- [x] Under "Mailing List", please update the [The Discussion Host mailing list](https://carpentries.topicbox.com/groups/groups/discussion-hosts) link to this one: https://carpentries.topicbox.com/groups/discussion-hosts
- [x] Under Mailing List, please add the final sentence paragraph: "If Topicbox is new to you, our [TopicBox Quick Start Guide](THEN ADD LINK TO THE COMMUNICATIONS RESOURCES WHERE THIS GUIDE IS IN THE HANDBOOK) will help you to set up your profile and give you an overview of how we use the platform on a day-to-day basis."
- [x] Under "Step-by-Step Guides" the link to Visit the [Communication and Collaboration Spaces section of this handbook](https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host#communication-and-collaboration-spaces) should be replaced with a link to the [Communications Resources](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/) section of the Handbook. 
- [x] Under "Before the Discussion Session", please change the link to [Learn about how to enable and use a waiting room as host.](https://support.zoom.us/hc/en-us/articles/115000332726-Waiting-Room#h_f493a86f-7d08-4e3b-9d6d-9b236fe9cdcd) to redirect to the relevant section in the Handbook rather than externally: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms#using-a-waiting-room 
- [x]  Under "Before the Discussion Session", please change the link to [Learn about how to use the host key to claim host access.](https://support.zoom.us/hc/en-us/articles/115001315866) to redirect to the relevant section in the Handbook rather than externally: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms#gaining-host-access
- [x] Under "Before the Discussion Session", please change the link to [Learn about how to enable automatic captioning](https://support.zoom.us/hc/en-us/articles/207279736-Managing-Zoom-closed-captioning-and-live-transcription-services) to redirect to the relevant section in the Handbook rather than externally: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms#closed-captioning
- [x] Under "During the Discussion" section, please change the link to [Learn more about how to set up and use breakout rooms](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms) to redirect to the exact/specific section in the Handbook: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/zoom_rooms#creating-breakout-rooms
- [x] Under "Cancelling a Discussion Session" please relace the link to the [Communication and Collaboration Spaces](https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host#communication-and-collaboration-spaces) with [Communication spaces](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/#communication-spaces)
- [x] Under "Script for Starting a Community Discussion", under the first bullet, please add a space between *Host should share the link in chat*:[Community Discussions Etherpad](https://pad.carpentries.org/community-discussions) AND then please italicise the "Host should share the link in the chat" under the third bullet. 
- [x] For uniformity in style, please revise the second to last bullet to read: *Host should share the link in chat*: [The Carpentries Code of Conduct Incident Report Form](https://goo.gl/forms/KoUfO53Za3apOuOK2)
Under the FAQs section, in answer to the question, "What if I do not know the answer to someone’s questions and no one in the room does either?" there is reference to the Carpentries mailing list. List should be plural.
- [x] "What if the host/co-host has a poor internet connection and is unable to communicate? What if Zoom fails to work (e.g. your internet connection fails)?" - please replace the link to contact the community via [our communication channels](https://carpentries-beta-handbook-preview.netlify.app/handbooks/community_session_host#communication-and-collaboration-spaces) with this one: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/#communication-spaces
- [x] "What if no one shows up?" - the link to the host form is not hyperlinked properly. 
- [x] "How can I become a Community Coordinator?" - please replace the "z" with "s" in formalized. 

---

**Comment by maneesha** [comment]
Addressed with #240
