### ISSUE TITLE
Updates to the Lesson Program Governor Handbook

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#220]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors

- [x] Under the Introduction, I would recommend that "Lesson Program Governance Committees (LPGCs)" links to the page I have recommended to be created on the new website [in this issue](https://github.com/carpentries/new-website/issues/273). 
- [x] Please end each bulleted point in the lists below with a full stop. 
- [x] Under "Advocacy:" and "Communication" please replace the two references to the "Executive Council" with "Board of Directors."
- [x] Under "Chair" replace the two references to the "Executive Council" with "Board of Directors." At 4th and 5th bullet points. 
- [x] Under "Onboarding" do not italicise the title of Greg's presentation, but rather hyperlink [session on How to Run a Meeting](https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors#how-to-run-a-meeting-presentation).
- [x] Under "Offboarding" please end each bulleted point in the lists below with a full stop.
- [x] Under "Etherpad", please begin the section with this sentence: "[The Carpentries uses Etherpad](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/etherpads) as a collaborative note-taking tool during workshops, training, and other Carpentries-related events." 
- [x] Under "Slack" reference to the Quick Guide should link to this: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists
- [x]   Under "TopicBox" please close off the section with a sentence paragraph that reads: "If you are new to Topicbox, please check out our [Topicbox Quick Start Guide](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists)."
- [ ] Under "Resources", the subheadings/title of the listed resources under this section - Lesson Program Governor Onboarding Presentation, LPGC Officer Onboarding Presentation, etc - are a different color not seen anywhere else for headings except under the Resources sections of this the [Maintainers Handbook](https://carpentries-beta-handbook-preview.netlify.app/handbooks/maintainers#resources), for one heading in the [Curriculum Advisors Handbook](https://carpentries-beta-handbook-preview.netlify.app/handbooks/curriculum_advisors#curriculum-onboarding-materials), and the headings in the [Lesson Developers Handbook](https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_developers#resources). Not sure why they differ and in that section only...
- [x] Under "Lesson Program Governance Policy" and "Committee Policy" replace reference to EC with BoDs. 
- [x] Also, please update link to "Lesson Program Governance Policy" to the link in new Handbook, which I think is this: https://carpentries-beta-handbook-preview.netlify.app/resources/curriculum/lesson-program-governance 
---

**Comment by maneesha** [comment]
Most points above are addressed in #237.
We can reconsider the point about the color of one of the headings in the other issues about colors/styles/fonts.  This is the defined style for `H4`.  If we want that style to be something else, we can consider it when we look at all the other styling.
