### ISSUE TITLE
Set up 404 page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#221]

**Comment by maneesha** [comment]
See [Generate 404 Not Found Pages Automatically for Sphinx Docs](https://sphinx-notfound-page.readthedocs.io/en/latest/)

**Comment by maneesha** [comment]
Opening this back up to set up the 404 page content.

**Comment by maneesha** [comment]
Taking off the "backend" tag as the backend work is complete.  We should consider what information we should share to make the 404 page useful.

**Comment by maneesha** [comment]
I put in #270 to get us started. Additional feedback is welcome.

**Comment by maneesha** [comment]
@OscarSiba Review the [404 page](https://carpentries-beta-handbook-preview.netlify.app/xyz) as it is now.  If you would like to add any other content, please note so here.  Otherwise you can close this issue.

**Comment by OscarSiba** [comment]
I am happy with this page as it is, thank you Maneesha.
