### ISSUE TITLE
Updates to the Maintainers Handbook

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#226]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/maintainers

- [x] Under "Roles and Responsibilities", please add full stops to the first set of bulleted points. In the second point, please remove the "Do" at the start of that sentence so that it reads "Not introduce new errors into the lesson". 
- [x] Under "Onboarding" please revise the text in bracket to read: (discuss@ on TopicBox, #general Slack channel)
- [x] Under "Communication and Collaboration Spaces", "Slack" should be a heading similar to the other communication spaces listed below. 
- [x] Entry for Slack is repeated twice. Here at the beginning, and then further down in this section. Please delete this first entry as it is, and replace it with the way the below entry is organised. But keep Slack as the first entry under this section. And then for the link to the Slack Quick Start Guide, please use this link: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists.
- [x] Then delete the bullet point that reads: "[The Maintainers mailing list](https://carpentries.topicbox.com/groups/groups/maintainers) is used for announcements relevant to Lesson Maintainers." - this information is captured further down under Topicbox. 
- [x] "Monthly Calls" (which is currently a bullet point under 'Slack') should also be its separate heading, with that text going below it. 
- [x] Under "Collaborative Notes", please begin the section with this sentence: "[The Carpentries uses Etherpad](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/etherpads) as a collaborative note-taking tool during workshops, training, and other Carpentries-related events."
- [x] Under "TopicBox" please close off the section with a sentence paragraph that reads: "If you are new to Topicbox, please check out our [Topicbox Quick Start Guide](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists)." 
- [x] Under "Informing Community Members about a Period of Absence" please remove the bolding on "You can also set a status on Slack", but link that sentence to the Slack Guide: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists. Leave the short description that is there. 
- [x] Under "Maintainer Onboarding Curriculum", the links to [tips for managing issues on a repository](https://carpentries.github.io/maintainer-onboarding/02-communicate-contributors/index.html#top-ten-tips-for-managing-issues-and-prs) and guidance for [tagging the Curriculum Team on issues and pull requests](https://carpentries.github.io/maintainer-onboarding/03-communicate-maintainers/index.html#tagging-in-the-curriculum-team) lead to a 404 error page. 

---

**Comment by maneesha** [comment]
Addressed with #236
