### ISSUE TITLE
Updates to the Lesson Developers Handbook

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#227]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_developers

- [x] Under "Communication and Collaboration Spaces", then under "Etherpad", please begin the section with this sentence: "[The Carpentries uses Etherpad](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/etherpads) as a collaborative note-taking tool during workshops, training, and other Carpentries-related events."
- [x]  Under "Slack" reference to the Quick Guide should link to this: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists 
- [x] Under "Mailing List" please close off the section with a sentence paragraph that reads: "If you are new to Topicbox, please check out our [Topicbox Quick Start Guide](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists)."

---

**Comment by maneesha** [comment]
Addressed with #234
