### ISSUE TITLE
Updates to Instructors Handbook

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#231]
---
On this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors

- [x] Under the Introduction, please hyperlink [Carpentries Instructor Training program](https://carpentries.github.io/instructor-training/)
- [x] Under "Roles and Responsibilities" please put full stops at the end of the two points. 
- [x] Please make **Time Expectation** bold. 
- [x] Under "Onboarding" please put a full stop after the 2 bolded sentences. The full stops must not be bold. 
- [x] The See our [Checkout Instructions](https://carpentries.github.io/instructor-training/checkout/index.html) page for more details, leads to a Page not found error. 
- [x] Under "No Shows" please hyperlink the email address instructor.training@carpentries.org.
- [x] Also, I think IMPORTANT: **Requests to re-register must be received within 7 days after the end date of the training. ** need to be bolded and on a separate line. 
- [x] Under "Partial Absence", after the Calendly link, please remove the extra full stop. 
- [x] Under "Checkout Extensions Policy" please hyperlink instructor.training@carpentries.org email in the last sentence. 
- [x] Under "Instructor Meetings" please change the hyperlinked text from "[Etherpad](https://pad.carpentries.org/InstructorMeetings)" to "[The Carpentries Instructor Monthly Meeting Etherpad]"
- [x] Under "Etherpad" do not italicise Instructor, and please start that section with the sentence: ""[The Carpentries uses Etherpad](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/etherpads) as a collaborative note-taking tool during workshops, training, and other Carpentries-related events."
- [x] Under "Slack" reference to the Quick Guide should link to this: https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists
- [x] Under "Mailing List" please close off the section with a sentence paragraph that reads: "If you are new to Topicbox, please check out our [Topicbox Quick Start Guide](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/slack-and-email#slack-and-mailing-lists)."
- [x] Under "Planning & Organising a workshop" please put full stops after each sentence. 
- [x] Under "Software Installation" under "On the day of:" - add a full stop at the end of that first sentence
- [x] Under "Using Exercises" some sentence lists don't have full stops. 
- [x] Under "General Tips", under "Introductions", the link for instructor training material should be this: https://carpentries.github.io/instructor-training/23-introductions.html
- [x] Under "Varying Skill Level", the link for Carpentries teaching practices should be this: https://carpentries.github.io/instructor-training/09-eia.html OR https://carpentries.github.io/instructor-training/24-practices.html - but I suspect the latter. 
- [x] Under [Curricula](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#curricula), there are two hyperlinked references to the "Core Curriculum". Please make sure they link to the relevant section of the new website: https://carp-new-website.netlify.app/workshops/host-workshop/#curriculum-requirements-for-centrally-organised-workshops
- [x] Under "Online workshop" please make sure the link to the Recommendation for Teaching Carpentries Workshops Online is now the new Handbook (rather than the old website which then links back to the old handbook): https://carpentries-beta-handbook-preview.netlify.app/resources/workshops/resources_for_online_workshops
- [x] Under [In-person workshop](https://carpentries-beta-handbook-preview.netlify.app/handbooks/instructors#in-person-workshop) the budget should be listed as$1500/ per Instructor.  
---

**Comment by maneesha** [comment]
Addressed with #241
