### ISSUE TITLE
Outdated links to CAC etherpads 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#239]

**Comment by maneesha** [comment]
From #213 

> The links to the Software Carpentry CAC pad, DC Geospatial CAC pad, and DC Genomics CAC pad lead to seemingly outdated pads. Not sure if there are more recent versions.

[See list here](https://carpentries-beta-handbook-preview.netlify.app/handbooks/curriculum_advisors#collaborative-notetaking).

**Comment by tobyhodges** [comment]
As far as I am aware, these are still the correct URLs. Unfortunately, some of our CACs have not met for some time.
