### ISSUE TITLE
Update and add communications links

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/handbook-beta#264]
---
Please update the Mastodon link to this one https://zenodo.org/records/14170125 on the following page:

- [ ] Under [Popular Resources](https://carpentries-beta-handbook-preview.netlify.app/#popular-resources)

Then, under [Communication Spaces](https://carpentries-beta-handbook-preview.netlify.app/resources/communications/#communication-spaces) please add the following links:

- [ ] [Mastodon](https://hachyderm.io/@thecarpentries)
- [ ] [LinkedIn](https://www.linkedin.com/company/the-carpentries/)
- [ ] [Blog](https://carpentries.org/blog/)
- [ ] [Newletter](https://carpentries.org/about-us/newsletter/)
- [ ] [YouTube](https://www.youtube.com/thecarpentries)

---

**Comment by maneesha** [comment]
Addressed with #265
