### ISSUE TITLE
Update footer with important links 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#73]
Footer should be updated with important links like the main Carpentries website.

**Comment by acrall** [comment]
@maneesha Can you clarify what you mean by this? When in a handbook, will the user be able to find the quick links in the navigation bar?

**Comment by maneesha** [comment]
What should go in the bottom footer that appears on all pages?  It currently looks like this:

![image](https://user-images.githubusercontent.com/829690/228613563-b65d3ab4-7962-4146-a112-64f786be1482.png)

**Comment by acrall** [comment]
I would leave the footer with having only that type of content. I would assume that it is easy to find a link to the website using the handbook navigation but that may need to be discussed. If not, maybe the footer could include a link back to the primary navigation page or home page?

**Comment by maneesha** [comment]
The header already has a link back to the home page, so I don't think we need to repeat that.  I wanted to see if anyone had ideas about any other specialized content we may want to include, sort of like we do on the [website](https://beta.carpentries.org/).

**Comment by Talishask** [comment]
My recommendations

**Section 1**
- Copyright Line
- Licensing information: This page is licensed under _
- Created using ...

**Section 2**
- [The Carpentries Website](linked to the website)
- [Our Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html)
- The Carpentries is a fiscally sponsored project of Community Initiatives, a registered 501(c)3 non-profit organisation. Please [donate](link to donate page).

**Comment by maneesha** [comment]
Fixed with #92
Links will still need to be updated - this is something we will need to do across the whole handbook once the handbook and website are both complete.
