### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#84]
The style guide can use the same formatting as the glossary, so the page structure will automatically be built, and items can be referenced in the same way.

**Comment by maneesha** [comment]
@acrall  is working on this separately; will incorporate into handbook when ready.

**Comment by maneesha** [comment]
@acrall  Will brand identity be part of the style guide?
I'm wondering, for example, about things like what we currently refer to for [colors](https://docs.carpentries.org/topic_folders/communications/resources/brand_identity.html) and [logos](https://docs.carpentries.org/topic_folders/communications/resources/logos.html).

**Comment by acrall** [comment]
@maneesha I currently have a "Style Guide" and a "Branding Guide" but wasn't sure if we wanted it to be in two separate guidebooks or all together in a "style and branding guide." I'm thinking the latter, but I have pulled the colours and logos content into the guidebooks I'm working on

**Comment by maneesha** [comment]
@OscarSiba Can you provide recommendations on what you would like to see here?

**Comment by maneesha** [comment]
Closing this as I am moving over the style guide and branding guide. We can consider other changes later.
