### ISSUE TITLE
Where should "Carpentries Commons" link to? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#99]
In our current handbook, there is a [page for Carpentries Commons](https://docs.carpentries.org/topic_folders/communications/resources/commons.html) that does not have much information and mainly links to the [Carpentries Commons repo](https://github.com/carpentries/commons). 

In the new handbook, should this intermediate page be there, or can we link directly to the Carpentry Commons repo? Assigning to @acrall just to answer the question; I'll take care of making it happen.

**Comment by acrall** [comment]
@maneesha We can link directly to the Commons repo from the handbook, removing the intermediate page

**Comment by maneesha** [comment]
Addressed with changes in #129
